### ISSUE TITLE
Fails to compile

### ISSUE THREAD

**Issue by vergilbg** [fachryansyah/react-mazer-ui#7]
I have followed the instruction on the npm https://www.npmjs.com/package/react-mazer-ui

1. Installed package by running `npm install react-mazer-ui --save`
2. Started my application by running `npm run start` which runs 'react-scripts --openssl-legacy-provider start'

The error I get is:

`./node_modules/react-mazer-ui/dist/index.js
Module not found: Can't resolve '../assets/css/app.css' in '...removed my personal directory\ClientApp\node_modules\react-mazer-ui\dist'`

I have tried:

1. Uninstalling and installing the package

**Comment by CoWayger** [comment]
Same problem here

**Comment by itsangelo92** [comment]
Same problem

**Comment by fachryansyah** [comment]
thanks for reporting this problem, consider solving this problem please use @0.1.1-alpha4 version
